---
- name: Playbook to Shutdown the RPi nodes in the cluster
  hosts: myrpicluster
  gather_facts: no
  tasks:
    - name: 'To Shutdown RPi'
      shell: shutdown 
      become: true

    - name: 'Save target host IP'
      set_fact:
        target_host: "{{ ansible_host }}"

    - name: 'wait for ssh to stop'
      wait_for: "port=22 host={{ target_host }} delay=10 state=stopped timeout=60"
      delegate_to: 127.0.0.1